version: "3.6"

services:
  postgres:
    build:
      context: .
    volumes:
      - "./copy:/copy"

  django:
    volumes:
      - "./copy:/copy"
      - "./django_project:/django_project"

  nginx:
    volumes:
      - "./copy:/copy"
