version: "3.6"

services:
  postgres:
    build:
      context: .
      dockerfile: docker/main/Dockerfile
    volumes:
      - "./docker/main/copy:/copy"
      - "./docker/utils.sh:/utils.sh"

  django:
    volumes:
      - "./docker/main/copy:/copy"
      - "./docker/utils.sh:/utils.sh"
      - "./django_project:/django_project"

  nginx:
    volumes:
      - "./docker/main/copy:/copy"
      - "./docker/utils.sh:/utils.sh"
      - "./docs:/docs"
