version: "3.2"

services:
  postgres:
    build:
      context: .
    volumes:
      - "./copy:/copy"

  django:
    volumes:
      - "./copy:/copy"
      - "./django_project:/django_project"
      - "./static:/static"

  nginx:
    volumes:
      - "./copy:/copy"
      - "./static:/static"
